### ISSUE TITLE
Typo in the program name, repo name and some of the output

### ISSUE THREAD

**Issue by Julepalme** [AvianNetwork/AvianPoolPicker#1]
A few misspellings of Avian as Avain, in both the program name / github repo name and in some of the output text strings.
Might wanna do a little refactoring / search and replace 👍

**Comment by decentralisedcoder** [comment]
Thanks I have just made those changes https://github.com/AvianNetwork/AvianPoolPicker/commit/65dc5398b39a0e8c5a589c531a9e1e7751ba0ce8 , we will get a new release pushed out asap.

**Comment by primitt** [comment]
Ok, getting a new release out.
